version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./etc/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - "1883:1883"
  telegraf:
    image: telegraf:alpine
    depends_on:
      - influxdb
      - kapacitor
      - chronograf
      - mosquitto
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  influxdb:
    image: influxdb:alpine
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./etc/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  kapacitor:
    image: kapacitor:alpine
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./etc/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
    ports:
      - "9092:9092"
  chronograf:
    image: chronograf:alpine
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    depends_on:
      - influxdb
      - kapacitor
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"

networks:
  internal:

volumes:
  influxdb:
  chronograf: