version: '3'
services:
  rabbitmq:
    container_name: piotserver_rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
  telegraf:
    container_name: piotserver_telegraf
    hostname: telegraf
    image: telegraf:1.18-alpine
    environment:
      INFLUXDB_USERNAME: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - influxdb
      - kapacitor
      - chronograf
      - rabbitmq
    restart: always
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  influxdb:
    container_name: piotserver_influxdb
    hostname: influxdb
    image: influxdb:2.0-alpine
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_ADMIN_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ADMIN_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket

      # INFLUXDB_DB: ${INFLUXDB_DB}
      # INFLUXDB_HTTP_AUTH_ENABLED: 1
      # INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      # INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      # INFLUXDB_WRITE_USER: ${INFLUXDB_WRITE_USER}
      # INFLUXDB_WRITE_USER_PASSWORD: ${INFLUXDB_WRITE_USER_PASSWORD}
    restart: always
    volumes:
      - ./etc/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /volume1/docker/piotserver_influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
  grafana:
    container_name: piotserver_grafana
    hostname: grafana
    build:
      context: grafana
      args:
        GF_INSTALL_PLUGINS: marcuscalidus-svg-panel,natel-plotly-panel
    depends_on:
      - influxdb
    restart: always
    volumes:
      - ./etc/grafana.ini:/etc/grafana/grafana.ini:ro
      - /volume1/docker/piotserver_grafana:/var/lib/grafana
    ports:
      - 3000:3000
