version: "3"
services:
  rabbitmq:
    container_name: piotserver_rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  telegraf:
    container_name: piotserver_telegraf
    hostname: telegraf
    image: telegraf:1.19-alpine
    environment:
      INFLUXDB_USERNAME: ${INFLUXDB_USERNAME}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_DATA_BUCKET: ${INFLUXDB_DATA_BUCKET}
      INFLUXDB_META_BUCKET: ${INFLUXDB_META_BUCKET}
      TELEGRAF_TOKEN: ${TELEGRAF_TOKEN}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - influxdb
      - rabbitmq
    restart: always
    volumes:
      - ${PWD}/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  influxdb:
    container_name: piotserver_influxdb
    hostname: influxdb
    image: influxdb:2.0-alpine
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_DATA_BUCKET}
      INFLUXDB_META_BUCKET: ${INFLUXDB_META_BUCKET}
    restart: always
    volumes:
      - ${PWD}/etc/influxdb:/etc/influxdb2
      - ${PWD}/scripts:/docker-entrypoint-initdb.d:ro
      - ${INFLUXDB_VOLUME_PATH}:/var/lib/influxdb2
    ports:
      - 8086:8086
  grafana:
    container_name: piotserver_grafana
    hostname: grafana
    image: grafana/grafana:8.0.4
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_INSTALL_PLUGINS: marcuscalidus-svg-panel
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    depends_on:
      - influxdb
    restart: always
    volumes:
      #- ${PWD}/etc/grafana.ini:/etc/grafana/grafana.ini:ro
      - ${GRAFANA_VOLUME_PATH}:/var/lib/grafana
      - ${GRAFANA_EXT_PATH}:/usr/share/grafana/public/ext:ro
    ports:
      - 3000:3000
  renderer:
    container_name: piotserver_renderer
    hostname: renderer
    image: grafana/grafana-image-renderer:3.0.0
    ports:
      - 8081
